#!/bin/bash
source `dirname $0`"/bashrc"

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
	echo "";
	echo "`basename $0`: Mark files for addition for \`vc_type\`."
	echo "    Also see \`git add --help\` and \`svn add --help\`."
	echo ""
	echo -e "${BIYellow}Usage:${Color_Off}"
	echo "    `basename $0`"
	echo ""
	echo -e "${BICyan}Valid options:${Color_Off}"
	echo "    -h [--help]    show this help message"
	echo ""
	echo -e "${BIWhite}Examples:${Color_Off}"
	echo "    `basename $0` README.md"
	echo ""
	exit 0
fi

vcType=`vc_type`

if [[ $vcType == 'git' ]]; then
	git add --verbose $@
elif [[ $vcType == 'svn' ]]; then
	svn add $@
fi

unset vcType
exit $?
