#!/bin/bash
source `dirname $0`"/bashrc"

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
	echo "";
	echo "`basename $0`: Run local instance of gulp inside node_modules folder instead of globally"
	echo "    installed version."
	echo ""
	echo -e "${BIYellow}Usage:${Color_Off}"
	echo "    `basename $0`"
	echo ""
	echo -e "${BICyan}Valid options:${Color_Off}"
	echo "    -h [--help]    show this help message"
	echo ""
	echo -e "${BIWhite}Examples:${Color_Off}"
	echo "    `basename $0`"
	echo ""
	exit 0
fi

./node_modules/.bin/gulp "$@"

exit $?
