#!/bin/bash
source `dirname $0`"/bashrc"

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
	echo "";
	echo "`basename $0`: Run local instance of gulp inside node_modules folder instead of globally"
	echo "    installed version."
	echo ""
	echo -e "${BIYellow}Usage:${Color_Off}"
	echo "    `basename $0`"
	echo ""
	echo -e "${BICyan}Valid options:${Color_Off}"
	echo "    -h [--help]    show this help message"
	echo ""
	echo -e "${BIWhite}Examples:${Color_Off}"
	echo "    `basename $0`"
	echo ""
	exit 0
fi

gulpFile="./gulpfile.js"
if [ ! -f "$gulpFile" ]; then
	gulpFile=`find . -name gulpfile.js | grep -v "node_modules" | head -n 1`
fi

if [ -f "./node_modules/.bin/gulp" ]; then
	./node_modules/.bin/gulp --gulpfile "$gulpFile" "$@"
else
	gulpModulesDir=`npm ls --depth=-1 | grep -v "─" | grep -v "^$" | sed "s/^.* //"`
	if [ -e "$gulpModulesDir/node_modules/.bin/gulp" ]; then
		$gulpModulesDir/node_modules/.bin/gulp --gulpfile "$gulpFile" "$@"
	else
		echo -e "${BIRed}Error:${Color_Off} can’t find local instance of gulp."
		exit 1
	fi
fi

unset gulpFile gulpModulesDir
exit $?
