#!/bin/bash
source `dirname $0`"/bashrc"

if [[ "$1" = "-h" || "$1" = "--help" || "$#" -gt "1" ]]; then
	echo "";
	echo "`basename $0`: Removes throttle added from \`throttle\`."
	echo ""
	echo -e "${BIYellow}Usage:${Color_Off}"
	echo "      `basename $0`"
	echo ""
	echo -e "${BICyan}Valid options:${Color_Off}"
	echo "      -h [--help]    show this help message"
	echo ""
	echo -e "${BIWhite}Examples:${Color_Off}"
	echo "      `basename $0`"
	echo ""
	exit 0
fi

sudo ipfw delete 1
