#!/bin/bash
source `dirname $0`"/bashrc"

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
	echo "";
	echo "`basename $0`: Throttles your internet speed to 50KByte/s or [SPEED]KByte/s."
	echo ""
	echo -e "${BIYellow}Usage:${Color_Off}"
	echo "      `basename $0` [SPEED]"
	echo ""
	echo -e "${BICyan}Valid options:${Color_Off}"
	echo "      -h [--help]    show this help message"
	echo ""
	echo -e "${BIWhite}Examples:${Color_Off}"
	echo "      `basename $0`"
	echo "      `basename $0` 100"
	echo ""
	exit 0
fi

if [[ "$#" -lt "1" ]]; then
	speed=50KByte/s
else
	speed=$1KByte/s
fi

sudo ipfw pipe 1 config bw $speed
sudo ipfw add 1 pipe 1 src-port 80
